#!/bin/sh

# Check the appsettings.json file is not being checked in.
# This contains the resource connection string which should not be checked in.
# If changes are being made to this file that should be checked in then
# git commit --no-verify can be used.
if git diff --cached --name-only | grep -qE 'appsettings.json'; then
  echo '======= COMMIT ERROR =======' >&2
  echo 'appsettings.json has been staged for commit.' >&2
  echo 'This often contains the resource connection string which should not be checked in to source control.' >&2
  echo 'If you do want to check in changes to this file use `git commit --no-verify`.' >&2
  echo 'Otherwise unstage this file.' >&2
  echo '============================' >&2
  exit 1;
fi

# Check a package-lock.json file is not being checked in.
# This repo uses rush with pnpm to manage dependencies and lock files.
# If changes are being made to this file that should be checked in then
# git commit --no-verify can be used.
if git diff --cached --name-only | grep -qE 'package-lock.json'; then
  echo '======= COMMIT ERROR =======' >&2
  echo 'package-lock.json has been staged for commit.' >&2
  echo 'This repo uses rush with pnpm to manage dependencies and lock files.' >&2
  echo 'Instead make changes to the package.json files and use `rush update`.' >&2
  echo 'If you do want to check in changes to this file use `git commit --no-verify`.' >&2
  echo 'Otherwise unstage this file.' >&2
  echo '============================' >&2
  exit 1;
fi

# Invoke the "rush prettier" custom command to reformat files whenever they
# are committed. The command is defined in common/config/rush/command-line.json
# and uses the "rush-prettier" autoinstaller.
npx --no-install rush prettier || exit $?
