// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

import React from 'react';
import {
  DefaultButton,
  IButtonProps,
  Icon,
  IStyle,
  mergeStyles,
  PrimaryButton,
  Spinner,
  Stack,
  Text,
  useTheme
} from '@fluentui/react';
import {
  containerStyle,
  moreDetailsStyles,
  containerItemGap,
  titleStyles,
  rejoinCallButtonContainerStyles
} from '../styles/SummaryEndCall.styles';
import { CallCompositeIcons } from '@azure/communication-react';
import { Video20Filled, CallEnd20Filled, SlideText20Regular } from '@fluentui/react-icons';
import { buttonWithIconStyles, rejoinButtonStyle, videoCameraIconStyle } from '../styles/StartCallButton.styles';
import { fetchTranscript } from '../utils/CallAutomationUtils';
/**
 * @private
 */
export interface SummaryEndCallScreenProps {
  iconName?: keyof CallCompositeIcons;
  disableStartCallButton?: boolean;
  pageStyle?: IStyle;
  callId?: string;
  summary?: string;
  summarizationStatus: 'InProgress' | 'Complete' | 'None';
  reJoinCall: () => void;
}

/**
 * Generic page with a title and more details text for serving up a notice to the user.
 *
 * @private
 */
export const SummaryEndCallScreen = (props: SummaryEndCallScreenProps): JSX.Element => {
  const { callId, summarizationStatus, summary, reJoinCall } = props;

  const theme = useTheme();

  return (
    <Stack
      className={mergeStyles(props.pageStyle)}
      verticalFill
      styles={{ root: { width: '100%' } }}
      verticalAlign="center"
      horizontalAlign="center"
      aria-atomic
    >
      <Stack className={mergeStyles(containerStyle)} tokens={containerItemGap}>
        <Stack>
          <CallEnd20Filled />
          <Text className={mergeStyles(titleStyles)} aria-live="assertive" role="alert">
            {'You left the call'}
          </Text>
          <Text className={mergeStyles(moreDetailsStyles)} aria-live="assertive">
            {'If this was a mistake , re-join the call.'}
          </Text>
          {!props.disableStartCallButton && (
            <Stack styles={rejoinCallButtonContainerStyles}>
              <StartCallButton
                className={mergeStyles(rejoinButtonStyle)}
                onClick={() => {
                  reJoinCall();
                }}
                disabled={false}
                rejoinCall={true}
                autoFocus
              />
            </Stack>
          )}
        </Stack>

        <Stack tokens={containerItemGap}>
          {summarizationStatus === 'InProgress' && (
            <Spinner styles={{ root: { marginTop: '2rem' } }} label="Summarizing conversation..." />
          )}
          {summarizationStatus === 'Complete' && summary && (
            <Stack
              styles={{
                root: {
                  width: '100%',
                  borderRadius: theme.effects.roundedCorner4,
                  boxShadow: theme.effects.elevation8
                }
              }}
            >
              <Stack styles={{ root: { padding: '1rem' } }}>
                <Text styles={{ root: { fontWeight: 600 } }} variant="large">
                  Meeting Summary
                </Text>
              </Stack>

              <Stack styles={{ root: { padding: '0 1rem' } }}>
                <Stack
                  styles={{
                    root: {
                      width: '100%',
                      height: '1px',
                      backgroundColor: theme.palette.neutralLight
                    }
                  }}
                />
              </Stack>

              <Stack tokens={{ childrenGap: '0.5rem', padding: '1rem' }}>
                <Stack horizontal tokens={{ childrenGap: '0.5rem' }} verticalAlign="center">
                  <Icon style={{ color: theme.palette.neutralSecondary }} iconName={'Info'}></Icon>
                  <Text styles={{ root: { fontWeight: 400, color: theme.palette.neutralSecondary } }}>
                    {'Generated by AI. Check for accuracy.'}
                  </Text>
                </Stack>
                <Text styles={{ root: { fontWeight: 400 } }}>{summary}</Text>
                <DefaultButton
                  text="Transcript"
                  onClick={async () => {
                    if (summary && callId) {
                      const transcript = await fetchTranscript(callId);
                      if (!transcript) {
                        console.error('Failed to fetch transcript');
                        return;
                      }
                      const transcriptionSentences = transcript.map(
                        (sentence) => sentence.participantId + ': ' + sentence.text
                      );
                      const blob = new Blob(transcriptionSentences, { type: 'text/plain' });
                      const url = URL.createObjectURL(blob);
                      const a = document.createElement('a');
                      a.href = url;
                      a.download = 'meeting-transcript.txt';
                      document.body.appendChild(a);
                      a.click();
                      document.body.removeChild(a);
                      URL.revokeObjectURL(url);
                    }
                  }}
                  styles={{
                    root: {
                      borderRadius: theme.effects.roundedCorner4,
                      borderColor: theme.palette.neutralTertiary,
                      minWidth: '5.75rem',
                      maxWidth: '6.5rem'
                    }
                  }}
                  onRenderIcon={() => <SlideText20Regular />}
                />
                <Text styles={{ root: { fontWeight: 400, color: theme.palette.neutralSecondary } }}>
                  {'Summary and transcript are held in memory and available shortly at the end of the meeting.'}
                </Text>
              </Stack>
            </Stack>
          )}
        </Stack>
      </Stack>
    </Stack>
  );
};

/**
 * @private
 */
export interface StartCallButtonProps extends IButtonProps {
  className?: string;
  /** If set, the button is intended to rejoin an existing call. */
  rejoinCall?: boolean;
  hideIcon?: boolean;
}

/**
 * @private
 */
const StartCallButton = (props: StartCallButtonProps): JSX.Element => {
  const { rejoinCall } = props;

  return (
    <PrimaryButton
      {...props}
      data-ui-id="call-composite-start-call-button"
      className={mergeStyles(props.className)}
      styles={buttonWithIconStyles}
      text={rejoinCall ? 'Re-join call' : 'Start call'}
      onRenderIcon={props.hideIcon ? undefined : () => <Video20Filled className={videoCameraIconStyle} />}
    />
  );
};
