// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

import { Message } from '@internal/react-components';

export const compareMessages = (
  firstMessage: Message<'chat' | 'system' | 'custom'>,
  secondMessage: Message<'chat' | 'system' | 'custom'>
): number => {
  if (firstMessage.payload.createdOn === undefined) return 1;
  if (secondMessage.payload.createdOn === undefined) return -1;
  const firstDate = new Date(firstMessage.payload.createdOn).getTime();
  const secondDate = new Date(secondMessage.payload.createdOn).getTime();
  // Workaround to get a stable order of message before we can get sequenceId from signaling
  // MessageIds are generated by time order the message persist, a good candidate other than time
  const idDelta =
    firstMessage.payload.messageId && secondMessage.payload.messageId
      ? Number.parseInt(firstMessage.payload.messageId) - Number.parseInt(secondMessage.payload.messageId)
      : 0;
  return firstDate - secondDate === 0 ? idDelta : firstDate - secondDate;
};
