import { NodeModulesPolyfillPlugin as esbuildPluginNodeModulePolyfills } from './node-modules-polyfill/index.js';
import NodeGlobalsPolyfillPluginPkg from '@esbuild-plugins/node-globals-polyfill';
import svg from 'esbuild-plugin-svg';
import alias from 'esbuild-plugin-alias';
import { htmlPlugin } from '@craftamap/esbuild-plugin-html';
import { build, serve } from 'esbuild';
import { readFileSync, writeFileSync } from 'fs';
import http from 'http';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const ROOT_DIR = path.resolve(__dirname, '..', '..', '..');
const SAMPLE_DIR = path.resolve(ROOT_DIR, 'samples', 'Calling');
console.log(`Project root: ${ROOT_DIR}`);
console.log(`Sample root: ${SAMPLE_DIR}`);

const { NodeGlobalsPolyfillPlugin } = NodeGlobalsPolyfillPluginPkg;

const pkgJSON = JSON.parse(readFileSync(path.resolve(SAMPLE_DIR, 'package.json')));

const esbuildOptions = {
  bundle: true,
  entryPoints: [path.resolve(SAMPLE_DIR, 'src/index.tsx')],
  logLevel: 'error',
  metafile: true, // Needed by `htmlPlugin`.
  outdir: path.resolve(SAMPLE_DIR, 'dist/esbuild'), // Needed by `htmlPlugin`.
  plugins: [
    alias({
      '@azure/communication-react': path.resolve(ROOT_DIR, 'packages/communication-react/src/index.ts'),
      '@internal/react-components': path.resolve(ROOT_DIR, 'packages/react-components/src/index.ts'),
      '@internal/react-composites': path.resolve(ROOT_DIR, 'packages/react-composites/src/index.ts'),
      '@internal/chat-stateful-client': path.resolve(ROOT_DIR, 'packages/chat-stateful-client/src/index.ts'),
      '@internal/chat-component-bindings': path.resolve(ROOT_DIR, 'packages/chat-component-bindings/src/index.ts'),
      '@internal/calling-stateful-client': path.resolve(ROOT_DIR, 'packages/calling-stateful-client/src/index.ts'),
      '@internal/calling-component-bindings': path.resolve(
        ROOT_DIR,
        'packages/calling-component-bindings/src/index.ts'
      ),
      '@internal/acs-ui-common': path.resolve(ROOT_DIR, 'packages/acs-ui-common/src/index.ts')
    }),
    NodeGlobalsPolyfillPlugin(),
    esbuildPluginNodeModulePolyfills(),
    htmlPlugin({
      files: [
        {
          define: {
            __CALLINGVERSION__: pkgJSON.dependencies['@azure/communication-calling'],
            __CHATVERSION__: pkgJSON.dependencies['@azure/communication-chat'],
            __COMMUNICATIONREACTVERSION__: pkgJSON.dependencies['@azure/communication-react'],
            __BUILDTIME__: new Date().toLocaleString()
          },
          entryPoints: ['src/index.tsx'],
          filename: 'index.html',
          htmlTemplate: `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="description" content="Azure Communication Services - UI Library: Call With Chat Sample app" />
  <title>UI Library Call With Chat Sample</title>
</head>

<body>
  <main id="root" class="Root"></main>
  <script type="text/javascript">
    window.FabricConfig = {};
    window.__CALLINGVERSION__ = '<%- define.__CALLINGVERSION__ %>';
    window.__CHATVERSION__ = '<%- define.__CHATVERSION__ %>';
    window.__COMMUNICATIONREACTVERSION__ = '<%- define.__COMMUNICATIONREACTVERSION__ %>';
    window.__BUILDTIME__ = '<%- define.__BUILDTIME__ %>';
  </script>
</body>
</html>
      `
        }
      ]
    }),
    svg()
  ],
  sourcemap: true
};

const API_HOST = 'localhost';
const API_PORT = '8080';
const API_PATHS = [
  '/token',
  '/refreshToken',
  '/isValidThread',
  '/createThread',
  '/userConfig',
  '/getEndpointUrl',
  '/addUser'
];

export async function serveIt() {
  const { host: esbuildHost, port: esbuildPort } = await serve(
    {
      servedir: path.resolve(SAMPLE_DIR, 'dist/esbuild') // index.html generated by `htmlPlugin`.
    },
    esbuildOptions
  );
  console.log(`esbuild started at ${esbuildHost}:${esbuildPort}`);
  console.log(`Head over to localhost:3000 to load your app!`);
  // Then start a proxy server on port 3000
  http
    .createServer((req, res) => {
      const hostname = isApiCall(req.url) ? API_HOST : esbuildHost;
      const port = isApiCall(req.url) ? API_PORT : esbuildPort;
      console.log(`Proxy ${req.url} -> ${hostname}:${port}`);
      // Forward each incoming request.
      const proxyReq = http.request(
        {
          hostname,
          port,
          path: req.url,
          method: req.method,
          headers: req.headers
        },
        (proxyRes) => {
          console.log(`Proxy response: ${proxyRes.statusCode}`);
          res.writeHead(proxyRes.statusCode, proxyRes.headers);
          proxyRes.pipe(res, { end: true });
        }
      );
      // Forward the body of the request.
      req.pipe(proxyReq, { end: true });
    })
    .listen(3000);
}

function isApiCall(url) {
  return API_PATHS.some((p) => url.startsWith(p));
}

export async function buildIt() {
  const result = await build(esbuildOptions);
  writeFileSync(path.resolve(SAMPLE_DIR, 'dist/esbuild/meta.json'), JSON.stringify(result.metafile, null, 2));
}
