# This is an official recommended way to skip a check when it is not necessary
# https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/troubleshooting-required-status-checks#handling-skipped-but-required-checks
name: Breaking Change Check

on:
  # Postsubmit CI on main.
  push:
    branches: [main]
  # Presubmit CI on PRs to all branches.
  pull_request:
    types: [labeled, unlabeled, opened, synchronize, reopened]
  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

# cancel workflow when a newer version of the workflow is triggered on the same github ref
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # get matrix for ci-jobs
  get_matrix:
    name: Set CI flavors
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'breaking-change') }}
    outputs:
      matrix: ${{ steps.get-matrix.outputs.matrix }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE so job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # Ensure node version is great enough
      - name: Use Node.js v16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - id: get-matrix
        run: echo "matrix=$(node ./common/scripts/workflow-read-matrix.mjs)" >> $GITHUB_OUTPUT

  check_breaking_changes:
    needs: get_matrix
    name: Check Breaking Changes
    if: ${{ github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'breaking-change') }}
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No breaking change check required"'
