name: CI

on:
  push:
  # Presubmit CI on PRs to all branches.
  pull_request:
  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

# cancel workflow when a newer version of the workflow is triggered on the same github ref
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  build_packages_1:
    name: 'Build Packages (webpack and tsc)'
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE so job can access it
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # Ensure node version is great enough
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      # Try get node_modules from cache
      - name: Restore node_modules from cache
        uses: actions/cache@v3
        with:
          path: common/temp/pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('common/config/rush/pnpm-lock.yaml') }}
      # Install dependencies
      - name: Install rush
        run: npm install -g @microsoft/rush
      - name: Install dependencies
        run: rush install --max-install-attempts 3

      # Builds
      - name: Build Packages
        run: rush build -t @azure/communication-react

      # Type check test folder
      # - must be run after building all packlets because it depends on compiled packlet dependencies
      # - must be run only on beta flavor build because the browser test code is not conditional compiled
      - name: Type check test folder
        run: cd packages/react-composites && rushx tsc:e2e

  #  build_packages_2:
  #    name: 'Build Packages (rsbuild and SWC)'
  #    runs-on: ubuntu-latest
  #    steps:
  #      # Checks-out your repository under $GITHUB_WORKSPACE so job can access it
  #      - uses: actions/checkout@v4
  #        with:
  #          fetch-depth: 0
  #      # Ensure node version is great enough
  #      - name: Use Node.js
  #        uses: actions/setup-node@v4
  #        with:
  #          node-version: 'lts/*'
  #      # Try get node_modules from cache
  #      - name: Restore node_modules from cache
  #        uses: actions/cache@v3
  #        with:
  #          path: common/temp/pnpm-store
  #          key: ${{ runner.os }}-${{ hashFiles('common/config/rush/pnpm-lock.yaml') }}
  #      # Install dependencies
  #      - name: Install rush
  #        run: npm install -g @microsoft/rush
  #      - name: Install dependencies
  #        run: rush install --max-install-attempts 3

  #      # Builds
  #      - name: Build Packages
  #        run: rush build -t @azure/communication-react

  #      # Type check test folder
  #      # - must be run after building all packlets because it depends on compiled packlet dependencies
  #      # - must be run only on beta flavor build because the browser test code is not conditional compiled
  #      - name: Type check test folder
  #        run: cd packages/react-composites && rushx tsc:e2e

  build_call_samples_1:
    name: 'Build Samples (webpack and tsc)'
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE so job can access it
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # Ensure node version is great enough
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      # Try get node_modules from cache
      - name: Restore node_modules from cache
        uses: actions/cache@v3
        with:
          path: common/temp/pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('common/config/rush/pnpm-lock.yaml') }}
      # Install dependencies
      - name: Install rush
        run: npm install -g @microsoft/rush
      - name: Install dependencies
        run: rush install --max-install-attempts 3
      # Build
      - name: Build Samples
        run: cd samples/Calling && npm run testwebpack

  build_call_samples_2:
    name: 'Build Samples (rsbuild)'
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE so job can access it
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # Ensure node version is great enough
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      # Try get node_modules from cache
      - name: Restore node_modules from cache
        uses: actions/cache@v3
        with:
          path: common/temp/pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('common/config/rush/pnpm-lock.yaml') }}
      # Install dependencies
      - name: Install rush
        run: npm install -g @microsoft/rush
      - name: Install dependencies
        run: rush install --max-install-attempts 3
      # Build
      - name: Build Samples
        run: cd samples/Calling && npm run rsbuild:build
