name: Generate APIView (feature)

on:
  workflow_dispatch:
    inputs:
      feature:
        description: 'Feature name. Must match the name of the feature in features.js.'
        required: true
        type: string

# cancel workflow when a newer version of the workflow is triggered on the same github ref
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ vars.RUNS_ON }}
    permissions: read-all
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE so job can access it
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          fetch-depth: 0
      # Ensure node version is great enough
      - name: Use Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 'lts/*'
      # Install dependencies
      - name: Install rush
        run: npm install -g @microsoft/rush@$(jq -r '.rushVersion' "rush.json")
      - name: Install dependencies
        run: rush install --max-install-attempts 3
      # Generate APIs
      - name: Generate APIs
        run: rush generate-api-diff --feature ${{ github.event.inputs.feature }}
      # Upload apis as artifact
      - name: Upload apis as action artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: apis
          path: apis/
