name: Nightly Localization

on:
  # Postsubmit CI on main.
  push:
    branches: [mgamis/test-pipeline]
  # Presubmit CI on PRs to all branches.
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  checkForChanges:
    name: Check for new changes
    runs-on: ubuntu-latest
    steps:
      # Get datetime
      - name: Get datetime for alpha release name
        id: datetime
        run: |
          echo "::set-output name=datetime::$(date +'%Y%m%d.%H%M')"

      - name: Hop into new branch
        run: git checkout -b localization/${{ steps.datetime.outputs.datetime }}

      - name: Trigger touchdown build pipeline
        uses: ./.github/workflows/azure-pipeline-action-fork
        with:
          azure-devops-project-url: 'https://skype.visualstudio.com/SCC/_build'
          azure-pipeline-name: 'Azure.communication-ui-library-touchdown-build-components'

      # Create a PR from the changes
      - name: Create PR
        run: |
          curl \
            -X POST \
            -H 'Accept: application/vnd.github.v3+json' \
            -H 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            https://api.github.com/repos/Azure/communication-ui-library/pulls \
            -d '{ "title":"${{ steps.version.outputs.version }} release branch", "head":"release/${{ steps.version.outputs.version }}", "base":"main", "body":"Release branch for ${{ steps.version.outputs.version }}. Created by the `Release branch - create` GitHub action. Please review." }'
