name: 'Pull Request Labeler'

on:
  pull_request:
    branches: [main]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v3
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          configuration-path: common/config/pr-labeler/pr-labeler-config.yml
          sync-labels: true
